name: taller2_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - matplotlib
      - numpy
      - opencv-python
      - scikit-image
      - scikit-learn
